stages:
  - build
  - dockerbuild
  - publish
  - deploy

build:eventservice:
  image: golang:1.8.1
  stage: build
  before_script:
    - mkdir -p $GOPATH/src/bitbucket.org/minamartinteam
    - ln -nfs $PWD $GOPATH/src/bitbucket.org/minamartinteam/myevents
    - cd $GOPATH/src/bitbucket.org/minamartinteam/myevents/src/eventservice
  script:
    - CGO_ENABLED=0 go build
  artifacts:
    paths:
      - src/eventservice/eventservice

build:bookingservice:
  image: golang:1.8.1
  stage: build
  before_script:
    - mkdir -p $GOPATH/src/bitbucket.org/minamartinteam
    - ln -nfs $PWD $GOPATH/src/bitbucket.org/minamartinteam/myevents
    - cd $GOPATH/src/bitbucket.org/minamartinteam/myevents/src/bookingservice
  script:
    - CGO_ENABLED=0 go build
  artifacts:
    paths:
      - src/bookingservice/bookingservice

dockerbuild:eventservice:
  image: docker:17.04.0-ce
  stage: dockerbuild
  dependencies:
    - build:eventservice
  script:
    - echo test
 #   - docker image build -t myevents/eventservice:$CI_COMMIT_REF_NAME src/eventservice
  only:
    - tags

dockerbuild:bookingservice:
  image: docker:17.04.0-ce
  stage: dockerbuild
  dependencies:
    - build:bookingservice
  script:
    - docker image build -t myevents/bookingservice:$CI_COMMIT_REF_NAME src/bookingservice
  only:
    - tags

publish:
  image: docker:17.04.0-ce
  stage: publish
  dependencies:
    - dockerbuild:eventservice
    - dockerbuild:bookingservice
  before_script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  script:
    - docker image push myevents/bookingservice:$CI_COMMIT_REF_NAME
    - docker image push myevents/eventservice:$CI_COMMIT_REF_NAME
  only:
    - tags

deploy:
  image: alpine:3.5
  stage: deploy
  environment: production
  before_script:
    - apk add --update openssl
    - wget -O /usr/local/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/v1.6.1/bin/linux/amd64/kubectl && chmod +x /usr/local/bin/kubectl
    - echo "$KUBE_CA_CERT" > ca.crt
    - kubectl config set-credentials gitlab-ci --token="${KUBE_TOKEN}"
    - kubectl config set-cluster your-cluster --server=https://your-cluster.example  --certificate-authority=ca.crt
    - kubectl config set-context your-cluster --cluster=your-cluster --user=gitlab-ci
    - kubectl config use-context your-cluster
  script:
    - kubectl set image deployment/eventservice api=myevents/eventservice:${CI_COMMIT_REF_NAME}
    - kubectl set image deployment/bookingservice api=myevents/bookingservice:${CI_COMMIT_REF_NAME}
  only:
    - tags