version: "3"
services:
  rmq:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
    logging:
      driver: none

  events:
    image: golang:1.7
    volumes:
      - ${GOPATH}/src/:/app/src
    environment:
      - GOPATH=/app
      - AMQP_URL=amqp://rmq:5672/
    working_dir: /app/src/bitbucket.org/minamartinteam/myevents/src/eventservice
    command: go run main.go

  booking:
    image: golang:1.7
    volumes:
      - ${GOPATH}/src/:/app/src
    environment:
      - GOPATH=/app
      - AMQP_URL=amqp://rmq:5672/
    working_dir: /app/src/bitbucket.org/minamartinteam/myevents/src/bookingservice
    command: go run main.go